<?php

namespace VMP\PortailBundle\Repository;

/**
 * AffairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffairesRepository extends \Doctrine\ORM\EntityRepository
{
}
