<?php

namespace VMP\PortailBundle\Repository;

/**
 * ChargesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargesRepository extends \Doctrine\ORM\EntityRepository
{
}
