<?php

namespace VMP\PortailBundle\Repository;

/**
 * PlanComptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanComptRepository extends \Doctrine\ORM\EntityRepository
{
}
