vmp_portail_bienvenue:
    path:     /Portail
    defaults:  { _controller: VMPPortailBundle:Advert:index }    
    
vmp_portail_view:
    path:     /Portail/compte/
    defaults: { _controller: VMPPortailBundle:Advert:view } 
    
vmp_portail_add:
    path:     /Portail/add
    defaults: { _controller: VMPPortailBundle:Advert:add }
    
vmp_portail_forms:
    path:     /Portail/forms
    defaults: { _controller: VMPPortailBundle:Advert:forms }    
    
vmp_portail_forma:
    path:     /Portail/forma
    defaults: { _controller: VMPPortailBundle:Advert:forma }             