vmp_portail_bienvenue:
    path:     /Portail
    defaults:  { _controller: VMPPortailBundle:Advert:index }    
    
vmp_portail_view:
    path:     /Portail/compte/
    defaults: { _controller: VMPPortailBundle:Advert:view } 
    
vmp_portail_add:
    path:     /Portail/add
    defaults: { _controller: VMPPortailBundle:Advert:add }
    
            